# Replica Settings
replicas:
  vote: 2
  result: 1
  worker: 1

# Image Registry
images:
  vote: jfrogartifact1.jfrog.io/artifactory/docker-trial/vote
  result: jfrogartifact1.jfrog.io/artifactory/docker-trial/result
  worker: jfrogartifact1.jfrog.io/artifactory/docker-trial/worker
  redis: redis:alpine
  db: postgres:15-alpine

# Ingress & HPA Toggles
ingress:
  enabled: true
  host: voting-app.local

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTarget: 50
