{{- range $name, $image := .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ index $.Values.replicas $name | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      # Required for private JFrog repo
      imagePullSecrets:
        - name: jfrog-secret
      containers:
      - name: {{ $name }}
        image: {{ $image }}
        {{- if or (eq $name "vote") (eq $name "result") }}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        {{- end }}
        env:
        {{- if eq $name "db" }}
        - name: POSTGRES_USER
          value: {{ $.Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ $.Values.postgres.password | quote }}
        {{- end }}
        {{- if eq $name "worker" }}
        - name: REDIS_HOST
          value: "redis"
        - name: POSTGRES_USER
          value: {{ $.Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ $.Values.postgres.password | quote }}
        {{- end }}
---
{{- end }}
