apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: {{ .Values.replicas.result }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      # --- ADDED IMAGE PULL STEP START ---
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      # --- ADDED IMAGE PULL STEP END ---
      containers:
      - name: result
        image: {{ .Values.images.result }}
        ports:
        - containerPort: 80
          name: result
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    # Optional: If you want a specific port for local testing
    {{- if .Values.services.result.nodePort }}
    nodePort: {{ .Values.services.result.nodePort }}
    {{- end }}
  selector:
    app: result
