{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $config.type }}
  ports:
  - port: {{ $config.port }}
    targetPort: {{ $config.port }}
  selector:
    app: {{ $name }}
---
{{- end }}
