name: Voting App CI/CD

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Login JFrog
      - name: Login to JFrog
        run: |
          docker login ${{ secrets.JF_URL }} \
          -u ${{ secrets.JF_USER }} \
          -p ${{ secrets.JF_PASSWORD }}

       # 1. Build Images with the correct Final Tag
      - name: Build and Tag Images
        run: |
          docker build -t ${{ secrets.JF_URL }}/docker-trial/vote:${{ github.run_number }} ./vote
          docker build -t ${{ secrets.JF_URL }}/docker-trial/result:${{ github.run_number }} ./result
          docker build -t ${{ secrets.JF_URL }}/docker-trial/worker:${{ github.run_number }} ./worker
          
          # Also tag as latest for convenience
          docker tag ${{ secrets.JF_URL }}/docker-trial/vote:${{ github.run_number }} ${{ secrets.JF_URL }}/docker-trial/vote:latest
          docker tag ${{ secrets.JF_URL }}/docker-trial/result:${{ github.run_number }} ${{ secrets.JF_URL }}/docker-trial/result:latest
          docker tag ${{ secrets.JF_URL }}/docker-trial/worker:${{ github.run_number }} ${{ secrets.JF_URL }}/docker-trial/worker:latest

      # 2. Push Images
      - name: Push Images
        run: |
          docker push ${{ secrets.JF_URL }}/docker-trial/vote:${{ github.run_number }}
          docker push ${{ secrets.JF_URL }}/docker-trial/vote:latest
          docker push ${{ secrets.JF_URL }}/docker-trial/result:${{ github.run_number }}
          docker push ${{ secrets.JF_URL }}/docker-trial/result:latest
          docker push ${{ secrets.JF_URL }}/docker-trial/worker:${{ github.run_number }}
          docker push ${{ secrets.JF_URL }}/docker-trial/worker:latest
      
      - name: Build number
        run: |
            echo "${{ github.run_number }}"
  

      - name: Trigger Deployment Restart
        run: |
           kubectl rollout restart deployment/vote -n vote
           kubectl create namespace vote || true
           helm upgrade --install voting-app ./helm-vote \
           --namespace vote \
           --create-namespace \
           -f ./helm-vote/values.yaml
           
            
          
          
